/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ServiceAreaRouteImport } from './routes/service-area'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as MotoRouteImport } from './routes/moto'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as AutoRouteImport } from './routes/auto'
import { Route as ApparelRouteImport } from './routes/apparel'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicSendQuoteRouteImport } from './routes/api/public/send-quote'
import { Route as ApiPublicCloudinarySignRouteImport } from './routes/api/public/cloudinary-sign'
import { Route as ApiPublicCalendlyWebhookRouteImport } from './routes/api/public/calendly-webhook'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreaRoute = ServiceAreaRouteImport.update({
  id: '/service-area',
  path: '/service-area',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const MotoRoute = MotoRouteImport.update({
  id: '/moto',
  path: '/moto',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoRoute = AutoRouteImport.update({
  id: '/auto',
  path: '/auto',
  getParentRoute: () => rootRouteImport,
} as any)
const ApparelRoute = ApparelRouteImport.update({
  id: '/apparel',
  path: '/apparel',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSendQuoteRoute = ApiPublicSendQuoteRouteImport.update({
  id: '/api/public/send-quote',
  path: '/api/public/send-quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCloudinarySignRoute = ApiPublicCloudinarySignRouteImport.update({
  id: '/api/public/cloudinary-sign',
  path: '/api/public/cloudinary-sign',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCalendlyWebhookRoute =
  ApiPublicCalendlyWebhookRouteImport.update({
    id: '/api/public/calendly-webhook',
    path: '/api/public/calendly-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apparel': typeof ApparelRoute
  '/auto': typeof AutoRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/moto': typeof MotoRoute
  '/quote': typeof QuoteRoute
  '/reviews': typeof ReviewsRoute
  '/service-area': typeof ServiceAreaRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/calendly-webhook': typeof ApiPublicCalendlyWebhookRoute
  '/api/public/cloudinary-sign': typeof ApiPublicCloudinarySignRoute
  '/api/public/send-quote': typeof ApiPublicSendQuoteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apparel': typeof ApparelRoute
  '/auto': typeof AutoRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/moto': typeof MotoRoute
  '/quote': typeof QuoteRoute
  '/reviews': typeof ReviewsRoute
  '/service-area': typeof ServiceAreaRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/calendly-webhook': typeof ApiPublicCalendlyWebhookRoute
  '/api/public/cloudinary-sign': typeof ApiPublicCloudinarySignRoute
  '/api/public/send-quote': typeof ApiPublicSendQuoteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apparel': typeof ApparelRoute
  '/auto': typeof AutoRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/moto': typeof MotoRoute
  '/quote': typeof QuoteRoute
  '/reviews': typeof ReviewsRoute
  '/service-area': typeof ServiceAreaRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/calendly-webhook': typeof ApiPublicCalendlyWebhookRoute
  '/api/public/cloudinary-sign': typeof ApiPublicCloudinarySignRoute
  '/api/public/send-quote': typeof ApiPublicSendQuoteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/apparel'
    | '/auto'
    | '/booking'
    | '/contact'
    | '/moto'
    | '/quote'
    | '/reviews'
    | '/service-area'
    | '/services'
    | '/sitemap.xml'
    | '/api/public/calendly-webhook'
    | '/api/public/cloudinary-sign'
    | '/api/public/send-quote'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/apparel'
    | '/auto'
    | '/booking'
    | '/contact'
    | '/moto'
    | '/quote'
    | '/reviews'
    | '/service-area'
    | '/services'
    | '/sitemap.xml'
    | '/api/public/calendly-webhook'
    | '/api/public/cloudinary-sign'
    | '/api/public/send-quote'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/apparel'
    | '/auto'
    | '/booking'
    | '/contact'
    | '/moto'
    | '/quote'
    | '/reviews'
    | '/service-area'
    | '/services'
    | '/sitemap.xml'
    | '/api/public/calendly-webhook'
    | '/api/public/cloudinary-sign'
    | '/api/public/send-quote'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApparelRoute: typeof ApparelRoute
  AutoRoute: typeof AutoRoute
  BookingRoute: typeof BookingRoute
  ContactRoute: typeof ContactRoute
  MotoRoute: typeof MotoRoute
  QuoteRoute: typeof QuoteRoute
  ReviewsRoute: typeof ReviewsRoute
  ServiceAreaRoute: typeof ServiceAreaRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicCalendlyWebhookRoute: typeof ApiPublicCalendlyWebhookRoute
  ApiPublicCloudinarySignRoute: typeof ApiPublicCloudinarySignRoute
  ApiPublicSendQuoteRoute: typeof ApiPublicSendQuoteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-area': {
      id: '/service-area'
      path: '/service-area'
      fullPath: '/service-area'
      preLoaderRoute: typeof ServiceAreaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moto': {
      id: '/moto'
      path: '/moto'
      fullPath: '/moto'
      preLoaderRoute: typeof MotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auto': {
      id: '/auto'
      path: '/auto'
      fullPath: '/auto'
      preLoaderRoute: typeof AutoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apparel': {
      id: '/apparel'
      path: '/apparel'
      fullPath: '/apparel'
      preLoaderRoute: typeof ApparelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/send-quote': {
      id: '/api/public/send-quote'
      path: '/api/public/send-quote'
      fullPath: '/api/public/send-quote'
      preLoaderRoute: typeof ApiPublicSendQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cloudinary-sign': {
      id: '/api/public/cloudinary-sign'
      path: '/api/public/cloudinary-sign'
      fullPath: '/api/public/cloudinary-sign'
      preLoaderRoute: typeof ApiPublicCloudinarySignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/calendly-webhook': {
      id: '/api/public/calendly-webhook'
      path: '/api/public/calendly-webhook'
      fullPath: '/api/public/calendly-webhook'
      preLoaderRoute: typeof ApiPublicCalendlyWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApparelRoute: ApparelRoute,
  AutoRoute: AutoRoute,
  BookingRoute: BookingRoute,
  ContactRoute: ContactRoute,
  MotoRoute: MotoRoute,
  QuoteRoute: QuoteRoute,
  ReviewsRoute: ReviewsRoute,
  ServiceAreaRoute: ServiceAreaRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicCalendlyWebhookRoute: ApiPublicCalendlyWebhookRoute,
  ApiPublicCloudinarySignRoute: ApiPublicCloudinarySignRoute,
  ApiPublicSendQuoteRoute: ApiPublicSendQuoteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
