/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ServiceAreaRouteImport } from './routes/service-area'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as MotoRouteImport } from './routes/moto'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConfirmRouteImport } from './routes/confirm'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as AutoRouteImport } from './routes/auto'
import { Route as ApparelRouteImport } from './routes/apparel'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminTasksRouteImport } from './routes/admin.tasks'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminQuotesRouteImport } from './routes/admin.quotes'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminAppointmentsRouteImport } from './routes/admin.appointments'
import { Route as ApiPublicSendQuoteRouteImport } from './routes/api/public/send-quote'
import { Route as ApiPublicCloudinarySignRouteImport } from './routes/api/public/cloudinary-sign'
import { Route as ApiPublicCalendlyWebhookRouteImport } from './routes/api/public/calendly-webhook'
import { Route as ApiPublicGoogleOauthCallbackRouteImport } from './routes/api/public/google.oauth-callback'
import { Route as ApiPublicGoogleDiagnoseRouteImport } from './routes/api/public/google.diagnose'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreaRoute = ServiceAreaRouteImport.update({
  id: '/service-area',
  path: '/service-area',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const MotoRoute = MotoRouteImport.update({
  id: '/moto',
  path: '/moto',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmRoute = ConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoRoute = AutoRouteImport.update({
  id: '/auto',
  path: '/auto',
  getParentRoute: () => rootRouteImport,
} as any)
const ApparelRoute = ApparelRouteImport.update({
  id: '/apparel',
  path: '/apparel',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTasksRoute = AdminTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuotesRoute = AdminQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAppointmentsRoute = AdminAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicSendQuoteRoute = ApiPublicSendQuoteRouteImport.update({
  id: '/api/public/send-quote',
  path: '/api/public/send-quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCloudinarySignRoute = ApiPublicCloudinarySignRouteImport.update({
  id: '/api/public/cloudinary-sign',
  path: '/api/public/cloudinary-sign',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCalendlyWebhookRoute =
  ApiPublicCalendlyWebhookRouteImport.update({
    id: '/api/public/calendly-webhook',
    path: '/api/public/calendly-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGoogleOauthCallbackRoute =
  ApiPublicGoogleOauthCallbackRouteImport.update({
    id: '/api/public/google/oauth-callback',
    path: '/api/public/google/oauth-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGoogleDiagnoseRoute = ApiPublicGoogleDiagnoseRouteImport.update({
  id: '/api/public/google/diagnose',
  path: '/api/public/google/diagnose',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/apparel': typeof ApparelRoute
  '/auto': typeof AutoRoute
  '/booking': typeof BookingRoute
  '/confirm': typeof ConfirmRoute
  '/contact': typeof ContactRoute
  '/moto': typeof MotoRoute
  '/quote': typeof QuoteRoute
  '/reviews': typeof ReviewsRoute
  '/schedule': typeof ScheduleRoute
  '/service-area': typeof ServiceAreaRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/calendly-webhook': typeof ApiPublicCalendlyWebhookRoute
  '/api/public/cloudinary-sign': typeof ApiPublicCloudinarySignRoute
  '/api/public/send-quote': typeof ApiPublicSendQuoteRoute
  '/api/public/google/diagnose': typeof ApiPublicGoogleDiagnoseRoute
  '/api/public/google/oauth-callback': typeof ApiPublicGoogleOauthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apparel': typeof ApparelRoute
  '/auto': typeof AutoRoute
  '/booking': typeof BookingRoute
  '/confirm': typeof ConfirmRoute
  '/contact': typeof ContactRoute
  '/moto': typeof MotoRoute
  '/quote': typeof QuoteRoute
  '/reviews': typeof ReviewsRoute
  '/schedule': typeof ScheduleRoute
  '/service-area': typeof ServiceAreaRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/calendly-webhook': typeof ApiPublicCalendlyWebhookRoute
  '/api/public/cloudinary-sign': typeof ApiPublicCloudinarySignRoute
  '/api/public/send-quote': typeof ApiPublicSendQuoteRoute
  '/api/public/google/diagnose': typeof ApiPublicGoogleDiagnoseRoute
  '/api/public/google/oauth-callback': typeof ApiPublicGoogleOauthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/apparel': typeof ApparelRoute
  '/auto': typeof AutoRoute
  '/booking': typeof BookingRoute
  '/confirm': typeof ConfirmRoute
  '/contact': typeof ContactRoute
  '/moto': typeof MotoRoute
  '/quote': typeof QuoteRoute
  '/reviews': typeof ReviewsRoute
  '/schedule': typeof ScheduleRoute
  '/service-area': typeof ServiceAreaRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/calendly-webhook': typeof ApiPublicCalendlyWebhookRoute
  '/api/public/cloudinary-sign': typeof ApiPublicCloudinarySignRoute
  '/api/public/send-quote': typeof ApiPublicSendQuoteRoute
  '/api/public/google/diagnose': typeof ApiPublicGoogleDiagnoseRoute
  '/api/public/google/oauth-callback': typeof ApiPublicGoogleOauthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/apparel'
    | '/auto'
    | '/booking'
    | '/confirm'
    | '/contact'
    | '/moto'
    | '/quote'
    | '/reviews'
    | '/schedule'
    | '/service-area'
    | '/services'
    | '/sitemap.xml'
    | '/admin/appointments'
    | '/admin/customers'
    | '/admin/quotes'
    | '/admin/settings'
    | '/admin/tasks'
    | '/admin/'
    | '/api/public/calendly-webhook'
    | '/api/public/cloudinary-sign'
    | '/api/public/send-quote'
    | '/api/public/google/diagnose'
    | '/api/public/google/oauth-callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/apparel'
    | '/auto'
    | '/booking'
    | '/confirm'
    | '/contact'
    | '/moto'
    | '/quote'
    | '/reviews'
    | '/schedule'
    | '/service-area'
    | '/services'
    | '/sitemap.xml'
    | '/admin/appointments'
    | '/admin/customers'
    | '/admin/quotes'
    | '/admin/settings'
    | '/admin/tasks'
    | '/admin'
    | '/api/public/calendly-webhook'
    | '/api/public/cloudinary-sign'
    | '/api/public/send-quote'
    | '/api/public/google/diagnose'
    | '/api/public/google/oauth-callback'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/apparel'
    | '/auto'
    | '/booking'
    | '/confirm'
    | '/contact'
    | '/moto'
    | '/quote'
    | '/reviews'
    | '/schedule'
    | '/service-area'
    | '/services'
    | '/sitemap.xml'
    | '/admin/appointments'
    | '/admin/customers'
    | '/admin/quotes'
    | '/admin/settings'
    | '/admin/tasks'
    | '/admin/'
    | '/api/public/calendly-webhook'
    | '/api/public/cloudinary-sign'
    | '/api/public/send-quote'
    | '/api/public/google/diagnose'
    | '/api/public/google/oauth-callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ApparelRoute: typeof ApparelRoute
  AutoRoute: typeof AutoRoute
  BookingRoute: typeof BookingRoute
  ConfirmRoute: typeof ConfirmRoute
  ContactRoute: typeof ContactRoute
  MotoRoute: typeof MotoRoute
  QuoteRoute: typeof QuoteRoute
  ReviewsRoute: typeof ReviewsRoute
  ScheduleRoute: typeof ScheduleRoute
  ServiceAreaRoute: typeof ServiceAreaRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicCalendlyWebhookRoute: typeof ApiPublicCalendlyWebhookRoute
  ApiPublicCloudinarySignRoute: typeof ApiPublicCloudinarySignRoute
  ApiPublicSendQuoteRoute: typeof ApiPublicSendQuoteRoute
  ApiPublicGoogleDiagnoseRoute: typeof ApiPublicGoogleDiagnoseRoute
  ApiPublicGoogleOauthCallbackRoute: typeof ApiPublicGoogleOauthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-area': {
      id: '/service-area'
      path: '/service-area'
      fullPath: '/service-area'
      preLoaderRoute: typeof ServiceAreaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moto': {
      id: '/moto'
      path: '/moto'
      fullPath: '/moto'
      preLoaderRoute: typeof MotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm': {
      id: '/confirm'
      path: '/confirm'
      fullPath: '/confirm'
      preLoaderRoute: typeof ConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auto': {
      id: '/auto'
      path: '/auto'
      fullPath: '/auto'
      preLoaderRoute: typeof AutoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apparel': {
      id: '/apparel'
      path: '/apparel'
      fullPath: '/apparel'
      preLoaderRoute: typeof ApparelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tasks': {
      id: '/admin/tasks'
      path: '/tasks'
      fullPath: '/admin/tasks'
      preLoaderRoute: typeof AdminTasksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quotes': {
      id: '/admin/quotes'
      path: '/quotes'
      fullPath: '/admin/quotes'
      preLoaderRoute: typeof AdminQuotesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/appointments': {
      id: '/admin/appointments'
      path: '/appointments'
      fullPath: '/admin/appointments'
      preLoaderRoute: typeof AdminAppointmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/send-quote': {
      id: '/api/public/send-quote'
      path: '/api/public/send-quote'
      fullPath: '/api/public/send-quote'
      preLoaderRoute: typeof ApiPublicSendQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cloudinary-sign': {
      id: '/api/public/cloudinary-sign'
      path: '/api/public/cloudinary-sign'
      fullPath: '/api/public/cloudinary-sign'
      preLoaderRoute: typeof ApiPublicCloudinarySignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/calendly-webhook': {
      id: '/api/public/calendly-webhook'
      path: '/api/public/calendly-webhook'
      fullPath: '/api/public/calendly-webhook'
      preLoaderRoute: typeof ApiPublicCalendlyWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/google/oauth-callback': {
      id: '/api/public/google/oauth-callback'
      path: '/api/public/google/oauth-callback'
      fullPath: '/api/public/google/oauth-callback'
      preLoaderRoute: typeof ApiPublicGoogleOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/google/diagnose': {
      id: '/api/public/google/diagnose'
      path: '/api/public/google/diagnose'
      fullPath: '/api/public/google/diagnose'
      preLoaderRoute: typeof ApiPublicGoogleDiagnoseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAppointmentsRoute: typeof AdminAppointmentsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminQuotesRoute: typeof AdminQuotesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTasksRoute: typeof AdminTasksRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAppointmentsRoute: AdminAppointmentsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminQuotesRoute: AdminQuotesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTasksRoute: AdminTasksRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ApparelRoute: ApparelRoute,
  AutoRoute: AutoRoute,
  BookingRoute: BookingRoute,
  ConfirmRoute: ConfirmRoute,
  ContactRoute: ContactRoute,
  MotoRoute: MotoRoute,
  QuoteRoute: QuoteRoute,
  ReviewsRoute: ReviewsRoute,
  ScheduleRoute: ScheduleRoute,
  ServiceAreaRoute: ServiceAreaRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicCalendlyWebhookRoute: ApiPublicCalendlyWebhookRoute,
  ApiPublicCloudinarySignRoute: ApiPublicCloudinarySignRoute,
  ApiPublicSendQuoteRoute: ApiPublicSendQuoteRoute,
  ApiPublicGoogleDiagnoseRoute: ApiPublicGoogleDiagnoseRoute,
  ApiPublicGoogleOauthCallbackRoute: ApiPublicGoogleOauthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
